import bcrypt from 'bcryptjs';


const data = {
  users: [
   { name: 'john',
    email: 'admin@gamil.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: true,
  },

   { name: 'jem',
    email: 'user@gamil.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: false,
  },
  ],
    products: [
       {
         name: 'Long Shirt',
         slug: 'long shirt',
         category: 'Shirt',
         image: '/images/shirt1.jpg',
         price: 40,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 8,
         countInStock: 10,
         description: 'A very nice shirt',
        },
       {
         name: 'Fit Shirt',
         slug: 'long shirt',
         category: 'Shirt',
         image: '/images/shirt2.jpg',
         price: 40,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 7,
         countInStock: 22,
         description: 'A very nice shirt',
        },
       {
         name: 'Short Shirt',
         slug: 'short shirt',
         category: 'Shirt',
         image: '/images/shirt3.jpg',
         price: 40,
         brand: 'Lee',
         rating: 4.5,
         numReviews: 7,
         countInStock: 22,
         description: 'A very nice shirt',
        },
       {
         name: 'Fit Pants',
         slug: 'fit pants',
         category: 'Pant',
         image: '/images/pants1.jpg',
         price: 40,
         brand: 'Oliver',
         rating: 4.5,
         numReviews: 7,
         countInStock: 12,
         description: 'A very nice pants',
        },
       {
         name: 'Slim Pants',
         slug: 'slim pants',
         category: 'Pant',
         image: '/images/pants2.jpg',
         price: 40,
         brand: 'Zara',
         rating: 4.5,
         numReviews: 7,
         countInStock: 12,
         description: 'A very nice pants',
        },
       {
         name: 'Classic Pants',
         slug: 'classic pants',
         category: 'Pant',
         image: '/images/pants3.jpg',
         price: 50,
         brand: 'Candy',
         rating: 4.5,
         numReviews: 7,
         countInStock: 12,
         description: 'A very nice pants',
        },

    ],
};
// db_user = ecom_next_23
// db_password = nCgrBRmGhjiCUL8D
export default data;